server:
  port: 8080

spring:
  application:
    name: contentflow


  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  datasource:
    url: jdbc:mysql://localhost:3306/contentflow3?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update


    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

cloudinary:
  cloud_name: dwfqsavsx
  api_key: 911959791416542
  api_secret: IbfJ3lzDkXhYonTIAqxAe51tvQ8

app:
  security:
    admin-master-key: "ADMIN@athenura123"

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: OFF

brevo:
  api:
    key:
  sender:
    email:
    name: